const projectInfo = [
  {
    id: 1,
    name: "Contact Keeper App",
    intro:
      "MERN Stack App, Contact keeper is used to store contact of user, you can edit,remove and update contact",
    image: "/images/contactkeeper.png",
    description:
      "This was a project I started back in november 2017 when I first learned python. I was the sole creator/developer for the first year of the project before I was able to hire help. The system stored fuel sample data for the entire lab and provided an interface for lab chemists and admins to view, add and send data to clients.Lab results would be generated by the system in PDF form and automatically sent to the client along with an interface for customers to be able to login and view.Customers had the ability to view all their data with a dynamic search form, trend data, add notes to reports and even map their samples' physical location.I worked on this system for 2 years before selling this to FOI Laboratories.",
    technologies: [
      "React Js",
      "Node + Express Framwork",
      "MongoDB (for Database)",
      "react-transition-group (for smooth transition)",
      "Context API (for managing app level state)",
    ],
  },
  {
    id: 2,
    name: "Github Finder",
    intro:
      "Github finder is used to find the user available in github using github API",
    image: "/images/githubfinder.png",
    description:
      "This was a project I started back in november 2017 when I first learned python. I was the sole creator/developer for the first year of the project before I was able to hire help. The system stored fuel sample data for the entire lab and provided an interface for lab chemists and admins to view, add and send data to clients.Lab results would be generated by the system in PDF form and automatically sent to the client along with an interface for customers to be able to login and view.Customers had the ability to view all their data with a dynamic search form, trend data, add notes to reports and even map their samples' physical location.I worked on this system for 2 years before selling this to FOI Laboratories.",
    technologies: [
      "React JS",
      "Github API",
      "Context API (for managing app level state)",
    ],
  },
  {
    id: 3,
    name: "Covid-19 Tracker",
    intro:
      "Covid-19 Tracker is used to track the live data of covid patients around the word",
    image: "/images/covid19-tracker.png",
    description:
      "This was a project I started back in november 2017 when I first learned python. I was the sole creator/developer for the first year of the project before I was able to hire help. The system stored fuel sample data for the entire lab and provided an interface for lab chemists and admins to view, add and send data to clients.Lab results would be generated by the system in PDF form and automatically sent to the client along with an interface for customers to be able to login and view.Customers had the ability to view all their data with a dynamic search form, trend data, add notes to reports and even map their samples' physical location.I worked on this system for 2 years before selling this to FOI Laboratories.",
    technologies: [
      "Python",
      "Django + Django REST Framework",
      "React JS",
      "Postgres",
      "AWS (S3 & RDS)",
      "Zingcharts - Trending & graphing test results",
      "Google Maps API",
      "XML2PDF - PDF generator",
    ],
  },
];

export default projectInfo;
